-- 코드를 작성해주세요
SELECT B.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO A ON T.PARENT_ITEM_ID = A.ITEM_ID
JOIN ITEM_INFO B ON T.ITEM_ID = B.ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY B.ITEM_ID DESC;