-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
FROM USED_GOODS_BOARD b , USED_GOODS_REPLY r
WHERE b.BOARD_ID = r.BOARD_ID
    AND b.CREATED_DATE LIKE '2022-10%'
ORDER BY r.CREATED_DATE asc, b.TITLE asc;